include theos/makefiles/common.mk

BUNDLE_NAME = pocketmodeswitch
pocketmodeswitch_FILES = Switch.x
pocketmodeswitch_FRAMEWORKS = UIKit
pocketmodeswitch_LIBRARIES = flipswitch
pocketmodeswitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk